<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdZ6HfS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdZ6HfS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEdZ6HfS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEdZ6HfS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEdZ6HfS\App_KernelDevDebugContainer([
    'container.build_hash' => 'EdZ6HfS',
    'container.build_id' => '1704f3bd',
    'container.build_time' => 1687907115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEdZ6HfS');
